name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  break:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [NLPModelsModifiers, NLPModelsIpopt]
        pkgversion: [master, stable]

    steps:
      - uses: actions/checkout@v2

      # imitation of a build process
      - name: Build
        run: echo "Building"

      - name: Save PR number
        env:
          PKG: ${{ matrix.pkg }}
          VERSION: ${{ matrix.pkgversion }}
        run: |
          mkdir -p ./pr
          echo "![](https://img.shields.io/badge/$PKG-Pass-green)" > ./pr/$PKG-$VERSION

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ./pr
          key: pr-folder

  upload:
    needs: break
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: ls
      - run: bash list-pkg.sh > pr/MSG

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/