name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  break:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [NLPModelsModifiers, NLPModelsIpopt]

    steps:
      - uses: actions/checkout@v2

      # imitation of a build process
      - name: Build
        run: echo "Building"

      - name: Save PR number
        env:
          PKG: ${{ matrix.pkg }}
        run: |
          mkdir -p ./pr
          echo "${{ github.event.number }}" > ./pr/NR
          echo "package: $PKG" > ./pr/$PKG
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/